### ISSUE TITLE
Please solve

### ISSUE THREAD

**Issue by sureshmariadass** [numbas/blackboard-scorm-analysis#3]
![image](https://user-images.githubusercontent.com/42803305/50278740-da2f7380-046d-11e9-9b78-97e478f49ba6.png)

**Comment by christianp** [comment]
It looks like this is related to pallets/werkzeug#1344, which is now fixed. Can you try reinstalling the requirements and let me know if you still get the error?

**Comment by abathur** [comment]
@christianp While the fix has been merged into master for Werkzeug, it hasn't been released yet.

**Comment by christianp** [comment]
@abathur thanks! I've started watching werkzeug for releases, so I'll close this once the fix has been released.

**Comment by christianp** [comment]
Werkzeug 0.15 has just been released, containing the fix for this problem. I'm closing this issue now.

**Comment by zaript** [comment]
I have the exact same issue with latest Werkzeug==1.16.0.

Traceback:
```
Traceback (most recent call last):
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/timurzarpov/.local/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/timurzarpov/src/blackboard-scorm-analysis/server.py", line 83, in upload_zip
    zip.extractall(extract_path)
  File "/usr/lib/python3.7/zipfile.py", line 1616, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/usr/lib/python3.7/zipfile.py", line 1669, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/lib/python3.7/zipfile.py", line 1480, in open
    self._fpclose, self._lock, lambda: self._writing)
  File "/usr/lib/python3.7/zipfile.py", line 722, in __init__
    self.seekable = file.seekable
AttributeError: 'SpooledTemporaryFile' object has no attribute 'seekable'
```

Packages installed:
```
~/s/blackboard-scorm-analysis (master|✚1) $ pip3 install -r requirements.txt
Requirement already satisfied: Flask in /home/timurzarpov/.local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (1.0.2)
Requirement already satisfied: lxml in /home/timurzarpov/.local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (4.3.0)
Requirement already satisfied: pygal in /home/timurzarpov/.local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (2.4.0)
Requirement already satisfied: click>=5.1 in /home/timurzarpov/.local/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (7.0)
Requirement already satisfied: Werkzeug>=0.14 in /home/timurzarpov/.local/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: Jinja2>=2.10 in /home/timurzarpov/.local/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (2.10.3)
Requirement already satisfied: itsdangerous>=0.24 in /home/timurzarpov/.local/lib/python3.7/site-packages (from Flask->-r requirements.txt (line 1)) (1.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/lib/python3/dist-packages (from Jinja2>=2.10->Flask->-r requirements.txt (line 1)) (1.1.0)
```
